#server:
#  port: 8000
#eureka:
#  instance:
#    hostname: eureka7003.com     # eureka服务端的实力名称
#  client:
#    fetch-registry: false  # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
#    register-with-eureka: false   # false表示自己不需要向注册中心注册自己
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址(单机版)

server:
  port: 8761
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: false #表示是否将自己注册到Eureka Server，默认是true。
    fetch-registry: false       #表示是否从Eureka Server获取注册信息，默认为true。
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/edu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1109
  application:
    name: eureka
feign:
  hystrix:
    enabled: true
